name: wechat_assets_picker_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  wechat_assets_picker:
    path: ../
  wechat_camera_picker: ^2.0.0-nullsafety.4

  extended_image: ^1.5.0
  path: ^1.8.0
  path_provider: ^2.0.0
  provider: ^5.0.0-nullsafety.5

dependency_overrides:
  path_provider: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
