name: wechat_assets_picker_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  wechat_assets_picker:
    path: ../
  wechat_camera_picker: ^1.1.2

dev_dependencies:
  flutter_asset_generator: ">=0.4.7 <2.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
