name: wechat_assets_picker_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  wechat_assets_picker:
    path: ../
  wechat_camera_picker: ^1.3.1
  extended_image: ^1.5.0
  path: 1.7.0
  path_provider: ^1.6.24
  provider: ^4.3.2+3

dependency_overrides:
  photo_manager: ">=0.6.0-dev.8 <2.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
