name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 5.0.0-nullsafety.5
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^1.5.0
  photo_manager: ^1.0.0-nullsafety.0
  provider: ^5.0.0-nullsafety.5
  video_player: ^2.0.0
