name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 2.2.1
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  assets_audio_player: ^2.0.6+1
  extended_image: ">=0.9.0 <2.0.0"
  flutter_common_exports: ^0.1.0
  photo_manager: ">=0.5.3+1 <2.0.0"
  provider: ^4.1.3
  video_player: ">=0.10.11+1 <2.0.0"
